In [3]:
import os
import pandas as pd

In [ ]:
url = ""
csv_name = ""

In [ ]:
os.system(f"wget {url} -O {csv_name}")

In [5]:
df = pd.read_stata("country_hsproduct2digit_year.dta")

In [6]:
df

,location_id,product_id,year,export_value,import_value,hs_eci,hs_coi,pci,location_code,hs_product_code
0,0,100,1994,0.0,59567.0,0.580963,-0.604102,-0.527114,ABW,01
1,0,100,1995,20344.0,72951.0,-0.502999,-0.713013,-0.541118,ABW,01
2,0,100,1996,0.0,85991.0,-0.681487,-0.709990,-0.641900,ABW,01
3,0,100,1997,0.0,30697.0,-1.290819,-0.824577,-0.494196,ABW,01
4,0,100,1998,0.0,22486.0,0.197883,-0.726349,-0.520908,ABW,01
...,...,...,...,...,...,...,...,...,...,...
628876,238,404,2016,0.0,0.0,NaN,NaN,0.153218,VIR,financial
628877,238,404,2017,0.0,0.0,NaN,NaN,-0.069907,VIR,financial
628878,238,404,2018,0.0,0.0,NaN,NaN,-0.402628,VIR,financial
628879,238,404,2019,0.0,0.0,NaN,NaN,-0.292228,VIR,financial
628880,238,404,2020,0.0,0.0,NaN,NaN,-0.276916,VIR,financial

In [13]:
import boto3


# This data contains srapppped websites
#https://commoncrawl.org/the-data/get-started/

#s3 = boto3.client('s3')
# s3://commoncrawl/crawl-data/CC-MAIN-2019-47
# s3.download_file('commoncrawl', 'CC-MAIN-2023-06/cc-index.paths.gz', 'myfile')

!wget https://data.commoncrawl.org/crawl-data/CC-MAIN-2022-05/segments/1642320299852.23/warc/CC-MAIN-20220116093137-20220116123137-00000.warc.gz

--2023-03-29 20:25:56--  https://data.commoncrawl.org/crawl-data/CC-MAIN-2022-05/segments/1642320299852.23/warc/CC-MAIN-20220116093137-20220116123137-00000.warc.gz
Resolving data.commoncrawl.org (data.commoncrawl.org)... 108.138.217.57, 108.138.217.109, 108.138.217.28, ...
Connecting to data.commoncrawl.org (data.commoncrawl.org)|108.138.217.57|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1150349388 (1,1G) [application/octet-stream]
Saving to: ‘CC-MAIN-20220116093137-20220116123137-00000.warc.gz’

CC-MAIN-20220116093 100%[===================>]   1,07G  47,7MB/s    in 23s

2023-03-29 20:26:19 (47,7 MB/s) - ‘CC-MAIN-20220116093137-20220116123137-00000.warc.gz’ saved [1150349388/1150349388]

In [ ]:
# others pending to explore


# google trends
# bigquery-public-data.google_trends
# can also be fetched by api
# https://lazarinastoy.com/the-ultimate-guide-to-pytrends-google-trends-api-with-python/

# inflation data
# bigquery-public-data.bls

# bitcoin transactions
# bigquery-public-data.crypto_bitcoin
    # interesting to see how they model the tables.
    # also posible to create a pipeline with the raw data
    #https://github.com/blockchain-etl/bitcoin-etl

# world events dataset
# gdelt-bq.gdeltv2
# https://www.gdeltproject.org/data.html#googlebigquery

#hacker news
# tech posts